apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.22.2
    app.quarkus.io/commit-id: 4532932f1f370d313dcdacc3836e68ab4c754a30
    app.quarkus.io/vcs-uri: https://github.com/port-experimental/ossf-scorecard-port-exporter.git
    app.quarkus.io/build-timestamp: 2025-05-21 - 15:38:26 +0000
  labels:
    app.kubernetes.io/name: ossf-scorecard-port-exporter
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: ossf-scorecard-port-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: ossf-scorecard-port-exporter
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.22.2
        app.quarkus.io/commit-id: 4532932f1f370d313dcdacc3836e68ab4c754a30
        app.quarkus.io/vcs-uri: https://github.com/port-experimental/ossf-scorecard-port-exporter.git
        app.quarkus.io/build-timestamp: 2025-05-21 - 15:38:26 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: ossf-scorecard-port-exporter
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OSSF_SCORECARD_REPO_URL
              value: 
            - name: PORT_CLIENT_SECRET
              value: 
            - name: PORT_INGEST_URL
              value: 
            - name: PORT_CLIENT_ID
              value: 
            - name: PORT_SCHEDULER_FREQUENCY
              value: 5m
          image: docker.io/sebi2706/ossf-scorecard-port-exporter:0.1
          imagePullPolicy: Always
          name: ossf-scorecard-port-exporter
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
